### PR TITLE
build: add commit lint

### PR DESCRIPTION
**Pull request by vinayakkulkarni**
- [x] Enables pre-commit & pre-push hooks to ensure there aren't any linting issues

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
OK.. I'll work on it tonight. Will update the PR.

**Comment by posva** [comment]
can you rebase this? The build seems to be good on CI

**Comment by vinayakkulkarni** [comment]
> can you rebase this? The build seems to be good on CI

Done

**Comment by posva** [comment]
It's weird it's still failing. I will checkout locally and merge locally

**Comment by posva** [comment]
I upgraded all deps and fixed the TS error, you can rebase again 😅

**Comment by vinayakkulkarni** [comment]
- [x] Rebased with latest changes

**Pull request merged**
