### PR TITLE
Document useRoute and useRouter

### PR DESCRIPTION
**Pull request by jeffreybiles**
A documentation partial solution to https://github.com/vuejs/vue-router-next/issues/257 - I'll look at creating a warning solution as well when I get time.

I'm not 100% sure whether the last sentence is technically correct.

### CODE REVIEW

**Comment by posva** [comment]
Thank you but I rather directly add the warnings I mentioned at https://github.com/vuejs/vue-router-next/issues/257#issuecomment-630706991

**Comment by jeffreybiles** [comment]
What about this PR without the final line?

I think `useRoute` and `useRouter` should be documented somewhere - I had to source dive to find them today, and only found them after being tipped by another GitHub issue.

**Comment by posva** [comment]
It's true it makes sense to add a note about them. I will add a note, it should compare it to `$route` and `$router` instead.

**Comment by jeffreybiles** [comment]
Sounds good.  Thank you!

**Comment by posva** [comment]
I didn't make sense to just add a note about those 2 functions so I added a note about the examples where people can find usage. The proper documentation will exist in a different place

**Pull request closed without merging**
